# 指定 docker compose 规范的版本
version: '3.8'

# 指定多个服务容器
services:
  # mongo服务容器
  mongo:
    # 设置容器基础镜像
    image: mongo
    # 设置容器端口映射
    ports:
      - 7733:27017
    # 设置容器数据卷挂载
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  # 设置node服务容器
  node:
    # 设置node服务容器从源码构建镜像，指定构建的上下文为当前文件所在的文件夹
    build: 
      context: .
    ports:
      # 暴露node-docker服务接口 
      - 3310:7744
      # 暴露node调试接口
      - 3311:9229
    # 设置环境变量
    environment:
      - SERVER_PORT=7744
      # 这里mongo就代表的是上面mongo服务名称，使用服务名称解决了容器ip变化问题（在网络章节中有详情说明）
      - MONGO_CLIENT_URL=mongodb://mongo:27017
    # 设置容器启动命令，以调试模式运行node服务
    command: npm run debug
    # 设置本地开发目录与容器内部/app目录关联映射，方便本地修改后同步到容器内部
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules


# 创建数据卷
volumes:
  mongodb:
  mongodb_config:

